### ISSUE TITLE
Python errors - no results

### ISSUE THREAD

**Issue by aviris** [isometry/alfredworkflows#8]
I use this (great) workflow quite a bit, but lately as soon as I started typing a word, Alfred would engage the fallback options. Using the debugger, I get the errors below. I tried updating terminology.py with "urllib2.URLError" to address the NameError, but it made no difference.  

OS 10.11.6, Python is 2.7.10

```python
[2016-08-08 12:25:19][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "terminology.py", line 53, in complete
    results = search_results(query)
  File "terminology.py", line 29, in search_results
    response = fetch_terms(query)
  File "terminology.py", line 22, in fetch_terms
    except URLError:
NameError: global name 'URLError' is not defined
[2016-08-08 12:25:19][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "terminology.py", line 53, in complete
    results = search_results(query)
  File "terminology.py", line 29, in search_results
    response = fetch_terms(query)
  File "terminology.py", line 22, in fetch_terms
    except URLError:
NameError: global name 'URLError' is not defined
[2016-08-08 12:25:20][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "terminology.py", line 53, in complete
    results = search_results(query)
  File "terminology.py", line 29, in search_results
    response = fetch_terms(query)
  File "terminology.py", line 22, in fetch_terms
    except URLError:
NameError: global name 'URLError' is not defined
```

**Comment by isometry** [comment]
Unfortunately, it appears that Agile Tortoise have now disabled their JSON API upon which my Terminology workflow depended to access the WordNet lexical database.
Installing their (free) Dictionary extension, may deliver similar functionality via `define <word>`: http://agiletortoise.com/terminology/mac/
Sorry.
